### ISSUE TITLE
Display tags associated with links displayed on the front page

### ISSUE THREAD

**Issue by darraghjburke** [ucsb-cs56-w20/mapache-search#125]
Once the tags team has created the tag entity and repository, we can query that for tags related to the front page links, and display those tags next to the link. This is another way to help users identify whether the link is relevant to them

- [x] A user should see all the tags that have been added to a link when that link appears on the front page.

**Comment by LouieAldana** [comment]
we could create a tag filter function. One that that allows the user to sort thru/ refine tags to their liking for a user-friendly experience. During the initial search, perhaps have the user enter a list that would be stored-- a list of random tags that would populate the page.
