### ISSUE TITLE
Add new tag creation button

### ISSUE THREAD

**Issue by benye11** [ucsb-cs56-w20/mapache-search#128]
In tag page, user should be able to create new tags via 'new tag creation button'.

You have the freedom to decide whether your button redirects to a new 'tag creation page' or not.

Follow-up on #114

**Comment by birded** [comment]
We will need to add a button(html) on the tag page that, when clicked, renders a text field and button which the user can input a new tag into. The tag will then need to be stored in the database tied to the user.
