### ISSUE TITLE
Allow search results to be sorted by timestamp

### ISSUE THREAD

**Issue by btk5h** [ucsb-cs56-w20/mapache-search#134]
As a user, I can sort the search results by their last updated date so that I can find the most up-to-date search results

**Comment by NandhaUCSB** [comment]
To do this, we will have to add a filter to the filter page to sort the results by date last updated. When selected, the matching results will be returned sorted in order by time of last update, from most to least recent.

**Comment by Ethkco** [comment]
- [ ] given the user is on the filtered search tab, when they input a date range to restrict the search to and then execute the search, then the search results should display only results in that date range
