### ISSUE TITLE
As an instructor I want to be able to view a random individual's vote and tag history so that I can use the random user information to determine possible future users' searches and votes.

### ISSUE THREAD

**Issue by jdavalos1** [ucsb-cs56-w20/mapache-search#137]
**Acceptance Criteria**
- In the main instructor page there will be a link that redirects the user to a page called Student Information Generator.
- In the Student Information Generator Page there will be a comment after the title that explains what the page does on button click and there will a button that generates a random student's information with title "Generate Random User"
- The "Generate Random User" button once clicked will redirect to another page where a random student's information will be displayed.
- The new random user page will display number of votes done, and if possible the links they have clicked.
- The button will be placed on the new random user page titled "Generate New Random User" which will generate a new random user and use the same random page to output the new random student's information.

**Comment by FrancieNagiki** [comment]
In the folder of mapache-search/src/main/resources/templates/instructor, create two .html file, one starter page with a button of starting generate the random individual, another result page to show the result.
Add Menu item for this generator.
Create a new controller for generate the random individual. Implement getRandomIndivdualStarter method and getRandomIndivdualResult method. In getRandomIndivdualResult method, get a random key and use the key to pick an individual.
