### ISSUE TITLE
As an instructor I want to be able to give permissions to users so that they can have the same access (data viewing, permission granting, etc.) as well.

### ISSUE THREAD

**Issue by jdavalos1** [ucsb-cs56-w20/mapache-search#140]

**Comment by stuartwayland** [comment]
In order to implement this, we would have to implement levels of access in the UsersController that would allow an admin to adjust access for the desired users. This would then be implemented as a  method in the adminController that they may invoke.

**Comment by jdavalos1** [comment]
I would recommend adding a new data type to hold the users privilege level. It could also be that @darraghjburke knows more about how to fetch privilege levels. I would recommend sending a message to the Slack page about this.
