### ISSUE TITLE
As a user I want a simple interface to specify my search filters - Add filter table on search page

### ISSUE THREAD

**Issue by maxcolbert** [ucsb-cs56-w20/mapache-search#143]

**Comment by tchao10** [comment]
Adding an interface for search filters would require adding additional HTML to the webpage. When a search is performed, the interface will be checked to see what filters should be applied.

**Comment by tchao10** [comment]
Branch name: w-5pm-b-search-filters-interface

**Comment by tchao10** [comment]
Acceptance Criteria:

- [ ] Given that the user is on the filtered search page, when the user wants to search by a specific website, then there is an input field where the user can type in websites
- [ ] Given that the user is on the filtered search page, when the user wants to restrict their search to results from within the past day/week/month/year, then there is a dropdown menu where the user can select one of the given timeframes
- [ ] Given that the user is on the filtered search page, when the user wants to sort the results by highest upvotes, then there is a checkbox where the user can enable this option
