### ISSUE TITLE
As a user I want to be able to filter my searches based on specific preferences - Implement google search API with filters (JSON)

### ISSUE THREAD

**Issue by maxcolbert** [ucsb-cs56-w20/mapache-search#146]

**Comment by Adarsha58** [comment]
To filter searches based on specific preferences, I could implement google search API to implement filters that google already has in its search engine. If the filter goes out of google search API, I may need to write my own code, or implement other API for that.

**Comment by Ethkco** [comment]
working on branch: w-5pm-b-google-search-api

**Comment by Ethkco** [comment]
Acceptance Criteria:

- [ ] Given the user is on the filtered search page, when they execute a filtered search, then the results will display a Google search with those filters, narrowed down to a select few programming help sites.
- [ ] Given the user is not on the filtered search page but on the non-filtered search home page instead, when they execute a search, the filtered search API will not be called. Instead a normal Google search will be executed, narrowed down to a select few programming help sites.
