### ISSUE TITLE
Display Teams that user is on

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-w20/mapache-search#149]
The GithubMembershipService already uses the github organization configured in application.properties to look up whether logged in users are members or not.

Take it a step further, and use the api to determine What team(s) the user is on (e.g. w-5pm-a).
This should be done in GithubMembershipService.

Store a list of those teams, comma separated, in a model variable (put this in AuthControllerAdvice.

Then, add a menu item: GitHub.  This menu item only shows up for users that are "members".

When you click it, you see a page that shows a list of all the teams of which the user is a member.

**Comment by kimsimonkim** [comment]
I would first write a code to store the list of the teams and formatted as described above, find a way to add a menu item that's available only for "members," then create a page to pop up once the menu item is created.

**Comment by DubiousLatchkey** [comment]
- [ ] There is a section of GithubController that makes a call to the GitHub API and gets the team data

- [ ] There is a table with all the teams that the currently logged in user is on

- [ ] There is a model variable in AuthControllerAdvice with a list of those teams
