### ISSUE TITLE
On GitHub page, add open PRs on project repos for the currently logged in user

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-w20/mapache-search#151]
On GitHub page, add open PRs on project repos for the currently logged in user

- [x] GitHub page displays only open PRs
- [x] GitHub page displays only from the user's PRs
- [x] Doesn't display any PRs if the user isn't logged in

**Comment by DubiousLatchkey** [comment]
In order to do this, I would just add a new controller to the GitHub page that uses the GitHub API to get the OAuthed user's PRs in a JSON.  It would then sort that data and add it to a table on the GitHub page.
