### ISSUE TITLE
Add list of project repos to application.properties

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-w20/mapache-search#152]
Add a property in application.properties called app.project_repos

It will be a comma separated list of particular repos in the organization that are associated with legacy code projects.  For example:

app.project_repos=ucsb-courses-search,mapache-search,open-lab-scheduler

Note that there should already be an application.properties setting for a github organization (e.g. ucsb-cs56-w20), and these repos are understood to be under that org.

Display the list of project repos on the GitHub page for members and admins, with a link to each repo.

**Comment by eduardogalvez** [comment]
To further test if the repos are accessible we can have tests that see if the repo itself is empty or what its contents are. Finding and adding a repo shouldn't be too complex as the repo has a unique name within a given organization.
