### ISSUE TITLE
Create a LinkController that has a route /link that has a param url that, when you go to it, redirects to that url.  (This the hook that you'll use in subsequent stories to build the database tables that store link clicks.)

### ISSUE THREAD

**Issue by darraghjburke** [ucsb-cs56-w20/mapache-search#155]
As a developer, I can have user's clicks link to an intermediate url and then redirect to the actual url so that information about the user's search is able to be collected.

- [x] Have the results in the search results route to this /link url
- [x] Have the LinkController redirect to the desired url

**Comment by briankangucsb** [comment]
Within the link controller, the counter for link clicks should be increased. Additionally, to implement this feature, we would need a new html file for the page the user is redirected to in the mapache-search/src/main/resources/templates/ directory. In that html file a button would need to be created that would redirect to the actual webpage.

**Comment by pconrad** [comment]
PR: https://github.com/ucsb-cs56-w20/mapache-search/pull/190

**Comment by pconrad** [comment]
Fixed in PR #190
