### ISSUE TITLE
When you hit the /link endpoint, a record should be created in the linksfollowed table with the link, the user id, the date/time.

### ISSUE THREAD

**Issue by darraghjburke** [ucsb-cs56-w20/mapache-search#158]
- [ ] We should see a new entry in the database every time a link is clicked
- [x] The entry should include the url that was clicked, the user id that clicked it, and the date/time of the click
- [x] We should see additional entries if a user clicks a link multiple times

**Comment by denversimmons** [comment]
When the user clicks a link, SearchController.java sends the user information to the database to be stored.

**Comment by briankangucsb** [comment]
#240
