### ISSUE TITLE
Replace the url on the search results with urls that redirect through /link?url=blah

### ISSUE THREAD

**Issue by darraghjburke** [ucsb-cs56-w20/mapache-search#159]
- [x] We want the links on the search results page to point to /link?... rather than the URL of the link
- [x] ~~We want to create a test that checks that the link on the search result page points to the correct URL~~ MOVED TO ISSUE #197

**Comment by tahereh-lab** [comment]
we can try to chang  result.html 
<td><a th:href="${ f.properties   }" th:text="${f.id}"></a></td>

**Comment by tahereh-lab** [comment]
change this line in result.html <td><a th:href="${    }" th:text="${f.id}"></a></td>

**Comment by DubiousLatchkey** [comment]
I just realized we did this as part of Issue #155, so I've moved this to under review as well and linked that PR here.

**Comment by pconrad** [comment]
I'm factoring out the creation of a test into a separate issue so that we can keep the team moving forward.

**Comment by pconrad** [comment]
Fixed in PR #190
