### ISSUE TITLE
Testing for `/link?url=` functionality.

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-w20/mapache-search#197]
This is a refactor from issue #159  

# Acceptance Criteria 

- [x] There is a test that checks whether results on the search result page redirect through a link such as `/link?url=https://stackoverflow.com/some/page/on/that/site` rather than linking to the site directly.

**Comment by DubiousLatchkey** [comment]
I made this test on issue #159 already, the PR is on https://github.com/ucsb-cs56-w20/mapache-search/pull/200

**Comment by pconrad** [comment]
@maxcolbert This is also not in https://github.com/ucsb-cs56-w20/FEEDBACK_w-6pm-a

We should not merge the PR without adding the points into the FEEDBACK Repo. 

If a PR gets merged and there's nothing int the FEEDBACK repo, the students earn nothing from all the work they did.
