### ISSUE TITLE
Each time a search is done, store that search in a new SearchQueries table.

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-w20/mapache-search#198]
This issue builds on #199 

Acceptance Criteria:

- [x] There is a table called `SearchQueries` that has fields for userid (this should probably be the github `uid` numeric field, not the `username`), timestamp, the id of the SearchTerm entry.  This will track who did the search, for what, and when.
- [x] Each time a user does a search, an record will be added to this table.   Note that we don't store the actual words searched for in this table (e.g. we don't store "Spring Boot Database") rather we store the id from the SearchTerms table of what the user searched for.
- [x] There is an admin only function (url tbd... we need to see what other admin functions already exist) that allows an admin to up to the 20 most recent entries in this table.  (Better ways of viewing this table are left for future issues---this is just an MVP view where we can at least see that the feature is working--not a finished UI for the admin!  Obviously, later on, admins are going to want to filter, and sort, etc. but that's for another issue, probably in a later quarter!)

**Comment by luhan68** [comment]
closing #198
