### ISSUE TITLE
Add a database table for search results.  At first, the only column that is needed is url.

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs56-w20/mapache-search#29]

**Comment by pconrad** [comment]
I think your first step is to add another `@Entity` class similar to to `src/main/java/edu/ucsb/cs56/mapache_search/entities/AppUser.java` 

It might be called `SearchResult.java`.

It will probably have only these data members:

```
  @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    private String url;
```

And then just getters/setters.

Then: add an`@Repository` similar to:

`src/main/java/edu/ucsb/cs56/mapache_search/repositories/UserRepository.java`

An `@Repository`  is the abstraction for a SQL database table.

You'll want a method:

```
   List<AppUser> findByUrl(String url); //any such attribute will work, as long as it's associated with the getter/setter
```

which allows you to lookup whether there is a search result with that url already.

**Comment by benye11** [comment]
Controller method and html file required as well.
